### ISSUE TITLE
Recompute UMAP not available

### ISSUE THREAD

**Issue by odespard** [MPI-Dortmund/tomotwin-cryoet#116]
Thank you for developing this useful tool. I have followed the tutorial using the example tomogram. The reference-based workflow works well and the clustering-based workflow works for the most part. However, I am not able to recompute the UMAP based on a cluster selected with the lasso tool. After lassoing a portion of the UMAP, the `Show target` and `Add candidate` buttons become active, but the `Recalculate UMAP` button remains greyed out and does not appear to become active even if I add the selected cluster as a candidate.

I can use the commands for Strategy 1 which lead to a similar result, but it would be convenient to be able to use the `Recalculate UMAP` feature as I presume is intended. 

It may of course be that I am doing something incorrectly in which case your guidance would be much appreciated. 

Many thanks,
Oscar

**Comment by GavinR1** [comment]
Hi Oscar,

The most likely cause of this error is that Napari isn't detecting any available GPUs on your system, which are needed for the UMAP recalculation. Can you comment if the system you are running napari on has dedicated GPUs? 

Unfortunately Napari also isn't working with X-forwarding so since the latest updates Napari needs to be running either on a dedicated workstation or via a virtual desktop in the case of eg. a cluster.

**Comment by odespard** [comment]
That makes sense. Unfortunately I can only access GPUs via compute nodes which are not able to display, so this is somewhat tricky. Nevertheless, this seems to be a problem on my end, so I'll close the issue. Thank you very much for clarifying it for me.

**Comment by odespard** [comment]
I've managed to run the software on a workstation, which is very useful. Thank you for your help. However, may I ask why the function doesn't work with X-forwarding in Napari? I can get Napari to open with X-forwarding and the rest of the plug-in seems to work, but the `Recalculate UMAP` button is still unavailable. I can import cuml and cudf in a separate Python script (so I would have expected check_if_gpu_available() in cluster_widget.py in napari_tomotwin to pass (which seems to be the issue in other versions). 

In addition, I thought that the UMAP function in cuml could run on CPUs in principle. Is there a reason for the strict GPU requirement in TomoTwin?

Thanks again.

**Comment by odespard** [comment]
Hello Daniel,

That's all very helpful to know with respect to Napari X-forwarding; I'll try to find out why it's the `Recalculate UMAP` button is still not working, but it's not a priority. Strategy 4 works well for me and permits the whole workflow to be run on a cluster, which is useful. Thank you for describing it.
