### ISSUE TITLE
Embedding ROI specification by binary mask 

### ISSUE THREAD

**Issue by thorstenwagner** [MPI-Dortmund/tomotwin-cryoet#24]
@rdrighetto & co from @CellArchLab made the suggestion to allow the specification of ROI for embedding a tomogram using a binary mask. Should be straight forward to implement.

**Comment by thorstenwagner** [comment]
Just pinging @cmccaffe - I will keep you posted here :-)

**Comment by thorstenwagner** [comment]
Implementation is done: https://github.com/MPI-Dortmund/tomotwin-cryoet/pull/27

We will release it probably next week.

**Comment by rdrighetto** [comment]
Amazing, thanks a lot @thorstenwagner!

**Comment by thorstenwagner** [comment]
Its done :-) 

https://github.com/MPI-Dortmund/tomotwin-cryoet/releases/tag/v0.5.0

I will close this issue. Reopen when necessary.
