### ISSUE TITLE
Installation returned an error

### ISSUE THREAD

**Issue by tailinhua16** [MPI-Dortmund/tomotwin-cryoet#3]
Hi,
I'm trying to install tomotwin but encountered an error, when ran the command 'mamba create xxxx', I got the following error:
Encountered problems while solving:
  - package cudatoolkit-11.6.0-habf752d_9 has constraint __cuda >=11.6.0 conflicting with __cuda-10.2-0
 
This happens no matter I use cuda-10.1 or cuda-11.8 in my shell (checked by nvcc --version), Any idea how to solve this problem?

Thank you very much in advance!
Sincerely,
Linhua Tai

**Comment by thorstenwagner** [comment]
Hi Linhau,

I think your problem is related to that issue:

https://github.com/mamba-org/mamba/issues/1267

this problems occurs when your CUDA/NVIDIA driver version is too old.

Can you update?

Best,
Thorsten

**Comment by tailinhua16** [comment]
Hi thorstenwagner,
thank you for your suggestion, I did what you sugeested, and interestingly, updating cuda from 10.1 to 11.8 didn't solve the problem, but updating cuda and nvidia driver to 11.8 and 520.61 did solve the problem. Now I can finally give tomotwin a try!
Thank you again for your help!
Sincerely,
Linhua Tai

**Comment by thorstenwagner** [comment]
Great :-)
