### ISSUE TITLE
note on installation: non-GPU pytorch installed 

### ISSUE THREAD

**Issue by nitishnih** [MPI-Dortmund/tomotwin-cryoet#41]
Hi,

While installing tomotwin as directed in the documentation, i.e., using the yml file, it seems mamba installs pytorch from conda-forge which by default is the non-GPU version. This is because conda-forge is on the top of the channels list. If I change the order of the channels, putting conda-forge below pytorch and nvidia, that correctly installs the CUDA enabled pytorch. For example:

```
name: tomotwin
channels:
  - nvidia
  - pytorch
  - rapidsai
  - conda-forge
  - defaults
```

I discovered this while building a container for tomotwin in a completely vanilla environment (no ~/.condarc for example).

**Comment by thorstenwagner** [comment]
Interesting. I'm doing quite a lot testing these days and I always get the gpu version with the current instructions.

Anyway I will change the order and test it, so that it works on both sides.

Thanks for taking the time and letting me know!

04.08.2023 21:32:17 nitish ***@***.***>:
