### ISSUE TITLE
libcublas.so.11 error

### ISSUE THREAD

**Issue by jychoi0616** [MPI-Dortmund/tomotwin-cryoet#42]
Dear tomotwin team,

Thanks for developing this software.
I just installed to our workstation (centos) and following your tutorial.
In this step: 
tomotwin_tools.py extractref --tomo TS_14.mrc --coords coords/reference.coords --out reference/ --filename protein_a

I got an error message of this:

ImportError: /data/miniconda3/envs/tomotwin/lib/python3.10/site-packages/cuml/internals/../../../.././libcublas.so.11: symbol cublasLtHSHMatmulAlgoInit, version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

When I went actual place of /data/miniconda3/envs/tomotwin/lib/, I couldn't list anything using "ls"command with the error message as this: 

ls: relocation error: /lib64/libacl.so.1: symbol getxattr, version ATTR_1.0 not defined in file libattr.so.1 with link time reference

Could you please help me in this please?

Thanks a lot!
Joy

**Comment by thorstenwagner** [comment]
Sorry, I hadnt the time to look into it. What was the problem? How did you fix it?

**Comment by jychoi0616** [comment]
Hi Thorsten,

It was some link issue between libcublas and libcublasLt (at least it seemed).
For my case, removing libcublas* under the torch/lib directory helped solving the issue by following one of the suggestions in https://github.com/hpcaitech/ColossalAI/issues/2901

Cheers,
Joy


On 18 Aug 2023, at 12:39, Thorsten Wagner ***@***.***> wrote:



Sorry, I hadnt the time to look into it. What was the problem? How did you fix it?

**Comment by thorstenwagner** [comment]
Is it possible that your PATH contains a path to cudotoolkit libs? Those might interfer with the one that comes with tomotwin.

18.08.2023 13:45:40 jychoi0616 ***@***.***>:

> 
> Hi Thorsten,
> 
> It was some link issue between libcublas and libcublasLt (at least it seemed).
> For my case, removing libcublas* under the torch/lib directory helped solving the issue by following one of the suggestions in https://github.com/hpcaitech/ColossalAI/issues/2901
> 
> Cheers,
> Joy
> 
>
