### ISSUE TITLE
memory issue of tomotwin_locate.py

### ISSUE THREAD

**Issue by jychoi0616** [MPI-Dortmund/tomotwin-cryoet#53]
Hi Thorsten,

I found tomotwin_locate.py tries to allocate more memory than the capacity of our workstation and it failed to run with the following error: 
OSError: [Errno 12] Cannot allocate memory

Is there an argument tag that I could add to make it use less memory and let it run?

Best wishes,
Joy

**Comment by thorstenwagner** [comment]
Could you run it with `--processes 2`? As more processes you use, as more memory it needs. 4 is the default.

**Comment by jychoi0616** [comment]
I tried with --processes 2, and still cannot allocate the memory, and i even tried with --processes 1, which had the same issue. My workstation has 11GB GDDR6 memory. Is this too low to process this job?

**Comment by thorstenwagner** [comment]
locate does not use any GPU. It depends on the RAM of your computer. How much RAM do you have?

Best,
Thorsten

**Comment by jychoi0616** [comment]
It seems 18GB memfree out of 131 GB total memory from cat /proc/meminfo. 
MemTotal:       131512552 kB
MemFree:        18046184 kB
MemAvailable:   37318316 kB

**Comment by jychoi0616** [comment]
Hi! It's 7.5G the one under out/embed/tomo directory. Is it too large?

**Comment by thorstenwagner** [comment]
It is actually quite big, but not too large. What dimensions did your tomogram had after rescaling it to 15A?

**Comment by jychoi0616** [comment]
I thought I had to rescale to 10A?

The dimension of my tomogram is:
Number of columns, rows, sections .....    1364    1920     400
 Map mode ..............................    2   (32-bit real)              
 Start cols, rows, sects, grid x,y,z ...    0     0     0    1364   1920    400

**Comment by thorstenwagner** [comment]
Yes, 10A is fine. I often do 15A when I picker larger proteins like ribosomes.

**Comment by thorstenwagner** [comment]
No further reactions. I think  this can be closed. Reopen if you are still interested.

**Comment by jychoi0616** [comment]
Thank you!! :)
