### ISSUE TITLE
Install tomotwin by mamba

### ISSUE THREAD

**Issue by kimdn** [MPI-Dortmund/tomotwin-cryoet#73]
I use mamba 0.11.2 and CentOS Linux release 7.8.2003

I tried
`mamba env create -n tomotwin -f https://raw.githubusercontent.com/MPI-Dortmund/tomotwin-cryoet/main/conda_env_tomotwin.yml`
according to [install instruction](https://tomotwin-cryoet.readthedocs.io/en/stable/installation.html#install-tomotwin).

However, I see

```
[kimd999@deception04 ~]$ mamba env create -n tomotwin -f https://raw.githubusercontent.com/MPI-Dortmund/tomotwin-cryoet/main/conda_env_tomotwin.yml
usage: mamba [-h] [--version] [--slow SLOW] [--enable-coverage] [--coverage-file COVERAGE_FILE] [--format FORMAT] [--no-color]
             [--tags TAGS]
             [specs ...]
mamba: error: unrecognized arguments: -n tomotwin
```

`conda env create -n tomotwin -f https://raw.githubusercontent.com/MPI-Dortmund/tomotwin-cryoet/main/conda_env_tomotwin.yml`
takes more than few hrs now, and it is still trying to solve conflicts.

Maybe tomotwin can be installed at [Ubuntu only](https://tomotwin-cryoet.readthedocs.io/en/stable/installation.html#system-requirements)?

**Comment by thorstenwagner** [comment]
No, I think the 3 years outdated mamba is the problem. Could you try:
```
mamba create -n tomotwin -c nvidia -c pytorch -c rapidsai -c conda-forge "pytorch>2.1" torchvision "pandas<2" scipy numpy matplotlib pytables cuml=23.04 cudatoolkit=11.8 "protobuf>3.20" tensorboard optuna mysql-connector-python
conda activate tomotwin
pip install tomotwin-cryoet
```

**Comment by kimdn** [comment]
Thanks. Indeed mamba 0.11.2 is too old.

By
`./Miniforge-pypy3-Linux-x86_64.sh`
I installed the latest mamba I believe

(base) [kimd999@deception01 bin]$ mamba --version
mamba 1.4.2
conda 23.3.1

However,

`mamba env create -n tomotwin -f https://raw.githubusercontent.com/MPI-Dortmund/tomotwin-cryoet/main/conda_env_tomotwin.yml`

gave me

```
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following packages are incompatible
├─ cudatoolkit 11.8**  is uninstallable because it conflicts with any installable versions previously reported;
└─ cuml 23.04**  is uninstallable because it requires
   └─ cudf 23.04.* , which requires
      └─ cupy >=9.5.0,<12.0.0a0 , which conflicts with any installable versions previously reported.
```

**Comment by kimdn** [comment]
Finally, I installed TomoTwin
![Screenshot 2023-11-07 at 7 03 38 PM](https://github.com/MPI-Dortmund/tomotwin-cryoet/assets/3903446/61aedba9-3a65-4c7c-9f0e-f4c70e384f71)

The solutions were 

removing most contents of ~/.condarc
from
```
[kimd999@tlogin1 ~]$ cat .condarc
auto_update_conda: false
auto_activate_base: false
channels:
  - defaults
  - conda-forge
  - nodefaults
channel_priority: strict
```

to
```
[kimd999@tlogin1 ~]$ cat .condarc
auto_activate_base: true
```

and cleaning old caches by
`mamba clean --all`


GPT4 taught me that I need to solve pre-existing conda channel priority issues when I reported
![Screenshot 2023-11-07 at 7 06 29 PM](https://github.com/MPI-Dortmund/tomotwin-cryoet/assets/3903446/bf782548-dbee-46ee-a8c0-64662f32571f)

also minor cache related warning indicated that I'd better do 
`mamba clean --all`

After removing most contents in ~/.condarc
and running `mamba clean --all`,
I didn't see any warnings and errors anymore when I retried
`mamba env create -n tomotwin -f https://raw.githubusercontent.com/MPI-Dortmund/tomotwin-cryoet/main/conda_env_tomotwin.yml`
