### ISSUE TITLE
napari_boxmanager by x-windows

### ISSUE THREAD

**Issue by kimdn** [MPI-Dortmund/tomotwin-cryoet#75]
I installed napari_boxmanager at my centos without any error and warning.

However, after I sshed into my Centos with -X (even I confirmed with xclock
![Screenshot 2023-11-08 at 11 00 13 AM](https://github.com/MPI-Dortmund/tomotwin-cryoet/assets/3903446/49da0d6e-7ea1-422f-87a7-62052ccdfe26)

), I can't open mrc.

For example, when I tried
![Screenshot 2023-11-08 at 11 01 42 AM](https://github.com/MPI-Dortmund/tomotwin-cryoet/assets/3903446/1dac84fb-2d14-4935-add2-c42126ad624e)

I see
![Screenshot 2023-11-08 at 10 58 43 AM](https://github.com/MPI-Dortmund/tomotwin-cryoet/assets/3903446/74f2bf78-d6e5-409f-bef6-693aeed454e5).

When I tried to open mrc by GUI (file -> open file
![Screenshot 2023-11-08 at 11 03 06 AM](https://github.com/MPI-Dortmund/tomotwin-cryoet/assets/3903446/e1b2006e-9e55-4b06-ab38-dee213484ebc)

), I see
![Screenshot 2023-11-08 at 10 57 42 AM](https://github.com/MPI-Dortmund/tomotwin-cryoet/assets/3903446/59e6f5b6-d308-4b19-9901-04a11f2e131d)

On the other hand, the same napari-tomotwin installation trial on my macOS opened mrc file well.
![Screenshot 2023-11-08 at 12 33 15 PM](https://github.com/MPI-Dortmund/tomotwin-cryoet/assets/3903446/74281fae-4c26-4a3e-b885-704d3c410ffb)

**Comment by thorstenwagner** [comment]
I'm afraid that napari has some issues with x-forwarding in general. Couldnt you mount maybe the external filesystem using for example sshfs?

**Comment by thorstenwagner** [comment]
As this issue is not active anymore, I close it.
