### ISSUE TITLE
TomoTwin_tools loads all tool dependencies

### ISSUE THREAD

**Issue by GavinR1** [MPI-Dortmund/tomotwin-cryoet#77]
tomotwin_tools.py will always load all tool dependencies regardless of which tools is used.

The effect of this is that if running on a cluster, you need to block a GPU node even if you don't use a gpu due to the cuml dependency for Umap, for example with calculating the median embedding or simply loading a help message from a tool.

**Comment by thorstenwagner** [comment]
PR #78 fixes the crash on non gpu machines.
