### ISSUE TITLE
Inquiry Regarding Model Training and Resource Requirements

### ISSUE THREAD

**Issue by JachyLikeCoding** [MPI-Dortmund/tomotwin-cryoet#80]
Dear Author,
I am interested in exploring the training process of TomoTwin, specifically regarding the model training and the associated hardware requirements.

Could you please provide insights into the following:

**Training Process**: Can you share details about the training pipeline for TomoTwin?  I see that this part of the tutorial has not been added yet.
**Resource Requirements**: What are the GPU memory and RAM requirements for training the global TomoTwin model? Any information on the hardware setup used during your experiments would be highly valuable.

I appreciate your time and expertise in this matter. Thank you for your contribution to the field.

**Comment by thorstenwagner** [comment]
Hi :-)

Here we are:
https://tomotwin-cryoet.readthedocs.io/en/latest/developer/devs.html#how-to-train-tomotwin

Best,
Thorsten

**Comment by JachyLikeCoding** [comment]
> Hi :-)
> 
> Here we are: https://tomotwin-cryoet.readthedocs.io/en/latest/developer/devs.html#how-to-train-tomotwin
> 
> Best, Thorsten

Thank you so much for your prompt response!
