### ISSUE TITLE
Adjusting license headers

### ISSUE THREAD

**Issue by kephale** [MPI-Dortmund/tomotwin-cryoet#95]
Would folks be open to switching the headers from containing the entire license text to something more concise like SPDX-License-Identifier headers?

https://spdx.org/licenses/MPL-2.0.html

It would simplify to something like:

```
# SPDX-License-Identifier: MPL-2.0
```

This would make it a lot easier to navigate the source code.

**Comment by thorstenwagner** [comment]
Very open! Do you want to make an PR? Otherwise i can do it in the next days.

22.02.2024 17:38:01 Kyle I S Harrington ***@***.***>:

**Comment by kephale** [comment]
Happy to submit the PR!
